[kernel]
totalTimeElements = 100
totalTimeNodes = 101
filename = "test3"
result_dir = "/home/shion/results/test_sdoftdg"
timeDomain = [0.0, 1.0]
timeElemLength = 0.01
# naturalFrequency = 345.57519
naturalFrequency1 = 125.664            # 0.20 complex
naturalFrequency2 = 160.221            # 0.255 real roots 
naturalFrequency = 188.495             # 0.3 complex 
dampingRatio = 0.0
quadTypeForTime = "GaussLegendre"
baseInterpolationForTime = "Lagrange"
baseTypeForTime = "Monomial"
timeOrder = 2
verbosity = 0
saveData = [true, false, false, false]
plotData = [true, false, false]
outputFreq = 1

[kernel.initialVel]
name = "initialVel"
returnType = "Scalar"
argType = "Constant"
value = 0.0

[kernel.initialDisp]
name = "initialDisp"
returnType = "Scalar"
argType = "Constant"
value = 1.0
